### ISSUE TITLE
style berishdagi hatolar

### ISSUE THREAD

**Issue by otabek-oktamov** [Mr-Perfectuz/countries#2]
![Screenshot_5](https://user-images.githubusercontent.com/79497492/145065354-9656a2d2-d662-4532-a0de-53fb0a37e492.png)
containerga nima uchun min-width berilganiga tushunmadim max-width berish kerak shunda mainga ham margin autolarni berishga hojat qolmaydi

**Comment by Mr-Perfectuz** [comment]
max-width ga o'zgartirildi
